### ISSUE TITLE
translated validation errors

### ISSUE THREAD

**Issue by multiscan** [epfl-si/people2#49]
Remove all hardcoded validation errors from models:

Instead of adding the error message into the validation statement in the model file

```
  validates :expertise_en, length: { maximum: EXPERTISE_MAX_LEN, message: "untranslated error message" }
```

add proper translation in the translation files:

```
en:
  activerecord:
    errors:
      models:
          profile:
            attributes:
              expertise_en:
                too_long: "Expertise is supposed to be a short list of keywords. Please keep it below %{count} characters"
```
